open! Core

(** A spell's level, and the band a parchment of it is drawn in.

    A parchment's name is the only thing on a floor that states its contents
    without stating their cost: "parchment of Fire Storm" and "parchment of
    Magic Dart" read identically in a list.

    The table is generated by joining crawl's [book-data.h] against
    [spl-data.h]. It covers all 132 spells a player book can carry, which is
    exactly the set the corpus holds, so a deeper fill needs no widening.

    Not version-keyed. The trigger for making it so is two served builds
    disagreeing about a spell's level -- not a build that merely lacks one,
    which resolves to [None] and renders as text. When it fires, key this the
    way [book_spells] is, on [(version_id, sub_type_id, spell_id)]. *)

module Tier : sig
  (** Crawl's own three-way split over spell level, from [tilepick.cc]: level 8+
      is [High], 5-7 is [Mid], the rest is [Low]. We keep crawl's thresholds
      while drawing our own art, so the bands mean the same thing to a reader
      who knows the game. *)
  type t =
    | Low
    | Mid
    | High
  [@@deriving compare, equal, sexp_of]

  val to_string : t -> string
  val of_level : int -> t
end

val level : string -> int option
val tier : string -> Tier.t option

(** [None] for anything that is not a parchment, and for a parchment naming a
    spell outside the table. Both render as text rather than a wrong tile. *)
val of_parchment : string -> Tier.t option

val known : string list
